[node]
type = "move_to"

[inputs]
flow = "FLOW"
goal_x = "FLOAT"
goal_y = "FLOAT"
goal_z = "FLOAT"

[outputs]
flow = "FLOW"
status = "BOOLEAN"

[qos]
reliability = "BestEffort"
durability = "TransientLocal"
history = "KeepLast"
deadline = 100  # Deadline in milliseconds

# [server]
# host = "localhost"
# port = 11111