[node]
type = "pick_goal"

[inputs]
flow = "FLOW"

[outputs]
flow = "FLOW"
altitude = "FLOAT"
yaw = "FLOAT"
vx = "FLOAT"
vy = "FLOAT"
vz = "FLOAT"

[qos]
reliability = "BestEffort"
durability = "TransientLocal"
history = "KeepLast"
deadline = 100  # Deadline in milliseconds

# [server]
# host = "localhost"
# port = 11111